---
# tasks file for java

- name: Ensure Java is installed.
  package:
    name: "{{ java_package }}"
    state: present

# Environment setup.
- name: Set JAVA_HOME if configured.
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home

- name: Ensure java is well installed
  shell: java -version